tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1
  android:
    - build-tools-24.0.2

flows:
  master:
    - call: sdk
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
  pr:
  - call: master

