tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1
  android:
    - 24.4.1

flows:
  master:
    - call: sdk
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    - echo y | android update sdk --no-ui --filter build-tools-24.0.2
  pr:
  - call: master

