tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1

  android:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - build-tools-24.0.3
    - android-23
    - android-24
    - extra-android-m2repository

flows:
  master:
    - call: verify
    - call: sdk
    - (name Fix permissions, silent) chmod a+x ./gradlew
    - (name Build) ./build.sh
  sdk:
    - (name Setup SDK properties) echo "sdk.dir=$ANDROID_SDK_HOME" > local.properties

  verify:
    - (name Show environment) env

  pr:
  - call: master

