tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1

  android:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - build-tools-24.0.3
    - android-15
    - android-16
    - android-17
    - android-18
    - android-19
    - android-20
    - android-21
    - android-22
    - android-23
    - android-24
    - Google Inc.:Google APIs:15
    - Google Inc.:Google APIs:16
    - Google Inc.:Google APIs:17
    - Google Inc.:Google APIs:18
    - Google Inc.:Google APIs:19
    - Google Inc.:Google APIs:21
    - Google Inc.:Google APIs:22
    - Google Inc.:Google APIs:23
    - Google Inc.:Google APIs:24
    - extra-android-m2repository

flows:
  master:
    - call: sdk
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=$ANDROID_SDK_HOME" > local.properties
  pr:
  - call: master

