tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1

  android:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - build-tools-24.0.3
    - android-15
    - android-16
    - android-17
    - android-18
    - android-19
    - android-20
    - android-21
    - android-22
    - android-23
    - android-24
    - extra-android-m2repository

flows:
  master:
    - call: verify
    - call: sdk
    - chmod a+x ./gradlew
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=$ANDROID_SDK_HOME" > local.properties

  verify:
    - ls -l $HOME/tools/android.hello-android-*/build-tools/23.0.3
    - ls -l $HOME/tools/android.hello-android-*/build-tools/23.0.3/*
  pr:
  - call: master

