tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1

  android:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - build-tools-24.0.3
    - android-23
    - android-24

flows:
  master:
    - call: verify
    - call: sdk
    - chmod a+x ./gradlew
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=$ANDROID_SDK_HOME" > local.properties

  verify:
    - env

  pr:
  - call: master

